language: node_js
node_js:
  - 12
script: echo "skip tests"
before_install:
- openssl aes-256-cbc -K $encrypted_a2f8bae31ff7_key -iv $encrypted_a2f8bae31ff7_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
